export const SKILL_ICON_MAP = {
  AI: "/icons/skills/ai.svg",
  Automation: "/icons/skills/automation.svg",
  AWS: "/icons/skills/AWS.webp",
  CSS: "/icons/skills/css3.webp",
  ETL: "/icons/skills/data_engineer.webp",
  Django: "/icons/skills/Django.webp",
  Docker: "/icons/skills/Docker.webp",
  FastAPI: "/icons/skills/FastAPI.webp",
  Git: "/icons/skills/Git.webp",
  GitHub: "/icons/skills/github.svg",
  HTML: "/icons/skills/HTML5.webp",
  JavaScript: "/icons/skills/JavaScript.webp",
  Linux: "/icons/skills/linux.svg",
  NoSQL: "/icons/skills/NoSQL.webp",
  Pandas: "/icons/skills/Pandas.webp",
  Dash: "/icons/skills/plotly_dash.webp",
  Plotly: "/icons/skills/plotly.webp",
  PostgreSQL: "/icons/skills/PostgreSQL.webp",
  Postman: "/icons/skills/postman.svg",
  "Python Dev": "/icons/skills/python_developer.webp",
  Python: "/icons/skills/python.webp",
  RAG: "/icons/skills/rag.svg",
  React: "/icons/skills/react.webp",
  Snowflake: "/icons/skills/snowflakes.webp",
  SQL: "/icons/skills/sql.svg",
  SQLite: "/icons/skills/SQLite.webp",
  "Tailwind CSS": "/icons/skills/tailwind.svg",
  TypeScript: "/icons/skills/TypeScript.webp",
  Vercel: "/icons/skills/vercel.svg",
  "Next.js": "/icons/skills/react.webp",
  "Prompt Engineering": "/icons/skills/ai.svg",
  "Vector Search": "/icons/skills/rag.svg",
  FAISS: "/icons/skills/ai.svg",
  NumPy: "/icons/skills/Pandas.webp",
  "Web Scraping": "/icons/skills/automation.svg",
  "REST API": "/icons/skills/FastAPI.webp",
  "AI Agent": "/icons/skills/ai.svg",
  Analytics: "/icons/skills/Pandas.webp",
  Snowflakes: "/icons/skills/snowflakes.webp",
  "Plotly Dash": "/icons/skills/plotly_dash.webp",
} as const;

export type SkillIconName = keyof typeof SKILL_ICON_MAP;

export function getSkillIconPath(name: string) {
  return SKILL_ICON_MAP[name as SkillIconName] ?? "/icons/skills/automation.svg";
}
